#!/bin/sh
#
# Copyright (C) 2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_VDR_EXTRAS_XPATH="/config/services/vdrextras"
OMV_VDR_SETUP_CONF="/etc/vdr/setup.conf"

[ "$(omv_config_get "${OMV_VDR_EXTRAS_XPATH}/live/enable")" != "1" ] && exit 0
[ "$(omv_config_get "${OMV_VDR_EXTRAS_XPATH}/streamdev/enable")" != "1" ] && exit 0

streamdev_port=$(omv_config_get "${OMV_VDR_EXTRAS_XPATH}/streamdev/port")

cat <<EOF >> ${OMV_VDR_SETUP_CONF}
live.StreamdevPort = ${streamdev_port}
EOF
