#!/bin/sh
#
# Copyright (C) 2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions
. /usr/share/openmediavault/scripts/vdr-extras-helper-functions

OMV_VDR_SETUP_CONF="/etc/vdr/setup.conf"

OMV_VDR_EXTRAS_STREAMDEV_HOSTS_CONF="/etc/vdr/plugins/streamdevhosts.conf"
OMV_VDR_EXTRAS_PLUGIN_XPATH="/config/services/vdrextras"

generate_setup_conf()
{
    local streamdev_port=$(omv_config_get "${OMV_VDR_EXTRAS_PLUGIN_XPATH}/streamdev/port")

    cat <<EOF >> ${OMV_VDR_SETUP_CONF}
streamdev-server.HTTPServerPort = ${streamdev_port}
EOF
}

generate_streamdev_conf()
{
    local allowed_hosts=$(omv_config_get "${OMV_VDR_EXTRAS_PLUGIN_XPATH}/streamdev/allowed_hosts")

    cat <<EOF > ${OMV_VDR_EXTRAS_STREAMDEV_HOSTS_CONF}
#
# streamdevhosts  This file describes a number of host addresses that
#                 are allowed to connect to the streamdev server running
#                 with the Video Disk Recorder (VDR) on this system.
# Syntax:
#
# IP-Address[/Netmask]
#

127.0.0.1             # always accept localhost
#192.168.100.0/24     # any host on the local net
#204.152.189.113      # a specific host
#239.255.0.0/16       # uncomment for IGMP multicast streaming
#0.0.0.0/0            # any host on any net (DON'T DO THAT! USE AUTHENTICATION)

# Allowed hosts from the OpenMediaVault VDR extras plugin.
${allowed_hosts}
EOF
}

enable=$(omv_config_get "${OMV_VDR_EXTRAS_PLUGIN_XPATH}/streamdev/enable")

if [ ${enable} -eq 0 ]; then
    disable_vdr_plugin "streamdev-server"
    exit 0
fi

generate_setup_conf
generate_streamdev_conf

enable_vdr_plugin "streamdev-server"
